version: '3.9'
services:
    mongodb:
        image: mongo:5.0.9-focal
        ports:
            - '${MONGODB_PORT}:27017'
        volumes:
            - ./mongodbdata:/data/db
        restart: always
        environment:
            MONGO_INITDB_DATABASE: '${MONGODB_DATABASE}'
            MONGO_INITDB_ROOT_USERNAME: '${MONGODB_USERNAME}'
            MONGO_INITDB_ROOT_PASSWORD: '${MONGODB_PASSWORD}'
        networks:
            - mida_test_1
    rabbitmq:
        image: rabbitmq:3.8-management-alpine
        ports:
            - '${RABBITMQ_PORT}:5672'
            - '${RABBITMQ_MANAGEMENT_PORT}:15672'
        volumes:
            - ./rabbitmq/data/:/var/lib/rabbitmq/
            - ./rabbitmq/log/:/var/log/rabbitmq/
        restart: always
        environment:
            RABBITMQ_ERLANG_COOKIE: cluster_cookie
            RABBITMQ_DEFAULT_USER: '${RABBITMQ_DEFAULT_USER}'
            RABBITMQ_DEFAULT_PASS: '${RABBITMQ_DEFAULT_PASS}'
        networks:
            - mida_test_1
networks:
    mida_test_1:
        driver: bridge
